=== RicardoSantom/2021_LMSGI_RST/ud04/pruebas/modelo.xsd
<?xml version="1.0"?>
<!--
Ricardo Santiago Tomé
11-02-2021
Validación de elementos simples
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="modelo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="curso">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="1"/>
                            <xs:maxInclusive value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="ciclo">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="DAW"/>
                            <xs:enumeration value="ASIR"/>
                            <xs:enumeration value="DAM"/>
                            <xs:enumeration value="SMR"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="nombreciclo">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="3"/>
                            <xs:maxLength value="100"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="codigoPostal">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[0-9]{5}"/>                           
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="comentario">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:whiteSpace value="preserve"/>
                        </xs:restriction>
                    </xs:simpleType>
                 </xs:element>
                 <xs:element name="temperatura">
                     <xs:simpleType>
                         <xs:restriction base="xs:decimal">
                             <xs:minInclusive value="-50"/>
                             <xs:maxInclusive value="50"/>
                             <xs:totalDigits value="5"/>
                             <xs:fractionDigits value="2"/>
                         </xs:restriction>
                     </xs:simpleType>
                 </xs:element>
                 <xs:element name="codigo">
                     <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="DAW|DAM|ASIR"/>
                        </xs:restriction>
                    </xs:simpleType>      
                 </xs:element>
                 <xs:element name="letter">
                     <xs:simpleType>
                        <xs:restriction base="xs:string">
                           <xs:minLength value="3"/>
                           <xs:pattern value="[A-ZÑ]([a-zA-ZñÑ ])*"/>
                        </xs:restriction>
                     </xs:simpleType>
                 </xs:element>
                 <xs:element name="profesor">
                     <xs:complexType>
                         <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="codP">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:pattern value="[A-Z]{3}"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="modulo" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                     </xs:complexType>
                 </xs:element>
            </xs:sequence>
        </xs:complexType>      
    </xs:element>
</xs:schema>

=== RicardoSantom/2021_LMSGI_RST/ud04/pruebas/modelo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<modelo
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='modelo.xsd'>
    <curso>1</curso>
    <ciclo>DAW</ciclo>
    <nombreciclo>Desarrollo de Aplicaciones Web</nombreciclo>
    <codigoPostal>49600</codigoPostal>
    <comentario>Este  ciclo es   muy difícil     para  mí</comentario>
    <temperatura>32.2</temperatura>
    <codigo>DAW</codigo>
    <letter>aaaaa</letter>
    <profesor codP="ARN" modulo="LM">Amor Rodríguez</profesor>
</modelo>
