=== RicardoSantom/2021_LMSGI_RST/ud04/03.1.dtd
<?xml version='1.0' encoding='UTF-8'?>
    <!ELEMENT descripcion (#PCDATA)>
    <!ELEMENT fecha EMPTY>
    <!ATTLIST fecha dia CDATA #REQUIRED
                     mes CDATA #REQUIRED
                    anyo CDATA #REQUIRED>
    <!ELEMENT hechoshistoricos (descripcion, fecha)>
    <!ELEMENT hechos (hechoshistoricos*)>

=== RicardoSantom/2021_LMSGI_RST/ud04/03.1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hechos SYSTEM '03.1.dtd'>
<hechos>
    <hechoshistoricos>
        <descripcion>Se funda Youtube</descripcion>
        <fecha dia='15' mes='2' anyo='2005'/>
    </hechoshistoricos>
    <hechoshistoricos>
        <descripcion>Se funda Google</descripcion>
        <fecha dia='4' mes='9' anyo='1998'/>
    </hechoshistoricos>
    <hechoshistoricos>
        <descripcion>Se funda Facebook</descripcion>
        <fecha dia='4' mes='2' anyo='2004'/>
    </hechoshistoricos>
</hechos>
