=== RicardoSantom/2021_LMSGI_RST/ud04/10.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
<xs:element name='horario'>
    <xs:complexType>
        <xs:sequence>
            <xs:element name='modulos' maxOccurs='unbounded'>
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:element name='modulo' type='xs:string'>
                            <xs:simpleType>
                                <xs:extension base='xs:string'>
                                     <xs:attribute name='codM' type='xs:ID'/>
                                 </xs:extension>
                            </xs:simpleType>
                        </xs:element>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
             <xs:element name='profesores' maxOccurs='unbounded'>
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:element name='profesor' type='xs:string'>
                            <xs:simpleType>
                                <xs:extension base='xs:string'>
                                    <xs:attribute name='codP' type='xs:ID'/>
                                </xs:extension>
                            </xs:simpleType>
                        </xs:element>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
             <xs:element name='imparte' maxOccurs='unbounded'>
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:element name='asignatura' type='xs:string'>
                            <xs:complexType>
                                <xs:extension base='xs:string'>
                                    <xs:attribute name='codP' type='xs:ID'/>
                                    <xs:attribute name='codM' type='xs:ID'/>
                                </xs:extension>
                            </xs:complexType>
                        </xs:element>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name='grupo' type='xs:string'>
                <xs:complexType>
                    <xs:attribute name='idgrupo' type='xs:string'/>
                    <xs:attribute name='codT' type='xs:string'/>
                    <xs:element name='hora' type='xs:string' minOccurs="0">
                        <xs:complexType>
                            <xs:attribute name='entrada' type='xs:string'/>
                            <xs:attribute name='salida' type='xs:string'/>
                            <xs:element name='dia_sem' type='xs:string'>
                                <xs:complexType>
                                    <xs:attribute name='dia'/>
                                     <xs:attribute name='num'/>
                                </xs:complexType>
                            </xs:element>
                        </xs:complexType>
                    </xs:element>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== RicardoSantom/2021_LMSGI_RST/ud04/10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE horario SYSTEM '10.dtd'>-->
<!DOCTYPE horario [
<!ELEMENT horario (modulos,profesores,imparte,grupo*)>
<!ATTLIST horario
    curso CDATA #IMPLIED
>
<!ELEMENT modulos (modulo)*>
<!ELEMENT modulo (#PCDATA)>
<!ATTLIST modulo 
     codM (EDD|LMSGI|PROG|BBDD|FOL|SINF|XXX)  #REQUIRED>
<!ELEMENT profesores (profesor*)>
<!ELEMENT profesor (#PCDATA)>
<!ATTLIST profesor
    codP  ID #REQUIRED>
<!ELEMENT imparte (asignatura)*>
<!ELEMENT asignatura EMPTY>
<!ATTLIST asignatura 
         codM (EDD|LMSGI|PROG|BBDD|FOL|SINF|XXX)  #REQUIRED
         codProfesor IDREFS #REQUIRED>
<!ELEMENT grupo (hora)*>
<!ATTLIST grupo
    idgrupo (DAW1|DAW2|SMR2|SMR1) #REQUIRED
    codT IDREF #REQUIRED><!--He modificado alguna de las horas porque no correspondían.-->
<!ELEMENT hora (dia_sem)*>
<!ATTLIST hora  
    entrada (08:30|09:20|10:10|11:00|11:50|12:15|13:05) #REQUIRED
    salida (09:20|10:10|11:00|11:50|13:05|13:55) #REQUIRED >
<!ELEMENT dia_sem (#PCDATA)>
<!ATTLIST dia_sem
    dia (lunes|martes|miercoles|jueves|viernes) #REQUIRED
    num (1|2)  "1" >
]>
<horario xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
         xsi:noNamespaceSchemaLocation='10.xsd'>
    <modulos>
        <modulo codM='EDD'>Entornos de Desarrollo</modulo>
        <modulo codM='LMSGI'>Lenguaje de Marcas</modulo>
        <modulo codM='PROG'>Programación</modulo>
        <modulo codM='BBDD'>Bases de Datos</modulo>
        <modulo codM='FOL'>Formación y Orientación Laboral</modulo>
        <modulo codM='SINF'>Sistemas informáticos</modulo>
    </modulos>
    <profesores>
        <profesor codP='MUP'>Marcos Unzueta Puente</profesor>
        <profesor codP='ARN'>Amor Rodríguez Navarro</profesor>
        <profesor codP='ACF'>Ambrosio Casado Fernández</profesor>
        <profesor codP='HRO'>Hermelinda Ramos Osorio</profesor>
        <profesor codP='MAM'>María del Cielo Alejo Mulas</profesor>
        <profesor codP='NCB'>Natividad Crespo Belver</profesor>
    </profesores>
    <imparte>
        <asignatura codM='EDD' codProfesor='MUP'></asignatura>
        <asignatura codM='LMSGI' codProfesor='ARN'></asignatura>
        <asignatura codM='PROG' codProfesor='ACF'></asignatura>
        <asignatura codM='BBDD' codProfesor='HRO'></asignatura>
        <asignatura codM='FOL' codProfesor='MAM'></asignatura>
        <asignatura codM='SINF' codProfesor='NCB'></asignatura>
    </imparte>
    <grupo idgrupo='DAW1' codT='MUP'>
        <hora entrada='08:30' salida='09:20'>          
            <dia_sem dia='lunes' num='1'>EDD</dia_sem>  
            <dia_sem dia='viernes' num='1'>EDD</dia_sem>
            
        </hora>
        <hora entrada='09:20' salida='11:00'>        
            <dia_sem dia='lunes' num='2'>SINF</dia_sem>  
            <dia_sem dia='viernes' num='2'>SINF</dia_sem> 
        </hora>
        <hora entrada='11:00' salida='11:50'>        
            <dia_sem dia='viernes' num='1'>FOL</dia_sem>
        </hora>
        <hora entrada='10:10' salida='11:00'>        
            <dia_sem dia="miercoles" num="1">FOL</dia_sem>  
        </hora>
        <hora entrada='11:00' salida='13:05'>        
            <dia_sem dia='lunes' num='2'>PROG</dia_sem>  
            <dia_sem dia='miercoles' num='2'>BBDD</dia_sem> 
        </hora>
        <hora entrada='13:05' salida='13:55'>        
            <dia_sem dia='lunes' num='1'>FOL</dia_sem>  
            <dia_sem dia='miercoles' num='1'>EDD</dia_sem> 
        </hora>
        <hora entrada='08:30' salida='10:10'>     
            <dia_sem dia='martes' num='2'>BBDD</dia_sem>  
            <dia_sem dia='miercoles' num='2'>PROG</dia_sem> 
            <dia_sem dia='jueves' num='2'>LMSGI</dia_sem> 
        </hora>
        <hora entrada='10:10' salida='11:50'>     
            <dia_sem dia='martes' num='2'>PROG</dia_sem>  
            <dia_sem dia='jueves' num='2'>PROG</dia_sem> 
        </hora>
        <hora entrada='12:15' salida='13:55'>     
            <dia_sem dia='martes' num='2'>LMSGI</dia_sem>  
            <dia_sem dia='jueves' num='2'>SINF</dia_sem> 
            <dia_sem dia='viernes' num='2'>BBDD</dia_sem> 
        </hora>
    </grupo>
</horario>
