<?xml version="1.0" encoding="UTF-8"?>
<!---->

<!DOCTYPE catalogo [
<!ELEMENT catalogo (portatil*)>
<!ATTLIST catalogo 
    xmlns:xsi CDATA #IMPLIED
    xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
<!ELEMENT portatil (referencia,nombre,fabricante,procesador,ram,disco,pantalla,grafica,foto*)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fabricante EMPTY>
<!ATTLIST fabricante 
    nombre (LENOVO|HP|MSI|APPLE|ASUS|DELL|DESCONOCIDO) #REQUIRED>
<!ELEMENT procesador (nombre,cache,numero,velocidad)*>
<!ELEMENT cache (#PCDATA)>
<!ATTLIST cache 
    tamanyo (Mb|Gb|Tb) "Gb">
<!ELEMENT numero (#PCDATA)>
<!ELEMENT velocidad (#PCDATA)>
<!ATTLIST velocidad 
    medida CDATA #FIXED "Ghz">
<!ELEMENT ram (memoria,tipo)>
<!ELEMENT memoria (#PCDATA)>
<!ATTLIST memoria 
    medida (Mb|Gb|Tb) "Gb">
 <!ELEMENT tipo (#PCDATA)>
<!ELEMENT disco (#PCDATA)>
<!ATTLIST disco 
    tipo (SSD|HDD) #REQUIRED
    medida (Mb|Gb|Tb) #REQUIRED>
    <!ELEMENT pantalla (dimension,resolucion,maxima?)>
    <!ELEMENT dimension (#PCDATA)>
    <!ELEMENT resolucion (#PCDATA)>
    <!ELEMENT maxima (#PCDATA)>
    <!ELEMENT grafica (#PCDATA)>
    <!ELEMENT foto (#PCDATA)>
]>
<catalogo xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
         xsi:noNamespaceSchemaLocation='11.xsd'>
    <portatil> 
        <referencia>HP102219</referencia>
        <nombre>PORTATIL HP 15-DA0204NS</nombre>
        <fabricante nombre="HP"/>
        <procesador>
            <nombre>Intel Core i3-7020U</nombre>
            <cache tamanyo="Gb">3</cache>
            <numero>2</numero>
            <velocidad medida="Ghz">5.3</velocidad>
        </procesador>
        <ram>
            <memoria medida="Gb">32</memoria>
            <tipo>DDR3</tipo>
        </ram>
        <disco tipo="SSD" medida="Gb">250</disco>
        <pantalla>
            <dimension>15.6 pulgadas</dimension>
            <resolucion>1266x768</resolucion>
            <maxima>1366x768</maxima>
        </pantalla>
        <grafica>Intel UHD Graphics 620</grafica>       
        <foto>foto1.png</foto>
        <foto>foto2.png</foto>       
    </portatil>
</catalogo>
